apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: ama-battle-api
spec:
  # 2 Pods should exist at all times.
  replicas: 1
  selector:
    matchLabels:
      app: ama-battle-api
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: ama-battle-api
    spec:
      containers:
        - name: ama-battle-api
          # Run this image
          image: ama-battle-api:1.0-SNAPSHOT
          env:
            - name: JAVA_OPTS
              value: "-Dconfig.resource=application.conf -Dplay.server.pidfile.path=/dev/null"
          ports:
            # application
            - name: http
              containerPort: 9000
          resources:
            limits:
              cpu: 0.1
              memory: 256Mi
            requests:
              cpu: 0.1
              memory: 256Mi
          command:
            - "/opt/docker/bin/battle-impl"
      volumes: []
