apiVersion: v1
kind: Service
metadata:
  name: battle
  namespace: ama
spec:
  clusterIP: None
  ports:
    - name: http
      port: 9000
      protocol: TCP
    - name: service-locator
      port: 9008
      protocol: TCP
    - name: remoting
      port: 2552
      protocol: TCP
    - name: management
      port: 8558
      protocol: TCP
  selector:
    app: battle
---
apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: battle
  namespace: ama
spec:
  # 2 Pods should exist at all times.
  replicas: 1
  selector:
    matchLabels:
      app: battle
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: battle
    spec:
      containers:
        - name: battle
          # Run this image
          image: golemiso/battle:1.0-SNAPSHOT
          env:
            - name: JAVA_OPTS
              value: "-Dconfig.resource=application.conf -Dplay.server.pidfile.path=/dev/null"
            - name: CASSANDRA_SERVICE_NAME
              value: cassandra
          ports:
            - name: http
              containerPort: 9000
            - name: service-locator
              containerPort: 9008
            - name: remoting
              containerPort: 2552
            - name: management
              containerPort: 8558
          resources:
            limits:
              cpu: 0.1
              memory: 256Mi
            requests:
              cpu: 0.1
              memory: 256Mi
          command:
            - "/opt/docker/bin/battle-impl"
      volumes: []
