apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ama-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: ama-web-gateway
              servicePort: 9000
      host: localhost
